version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: .
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NACOS_SERVER=123.57.145.79:8848
      - SERVICE_PORT=8000
      - ENVIRONMENT=production
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=no5groupnacos
      - NACOS_HEARTBEAT_INTERVAL=5
      - NACOS_HEARTBEAT_TIMEOUT=5
      - START_TIME=${START_TIME:-$(date +%s)}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
