# Generated by Django 5.2 on 2025-08-28 07:41

import django.db.models.deletion
import minio_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.SmallIntegerField(choices=[(0, '上架'), (1, '封禁'), (2, '已出售'), (3, '未审核')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.SmallIntegerField(choices=[(0, '包邮'), (1, '自提')], default=0)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=0.0, help_text='平均评分', max_digits=2)),
                ('categories', models.ManyToManyField(related_name='products', to='Product.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('media_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media', models.ImageField(blank=True, null=True, storage=minio_storage.storage.MinioMediaStorage(), upload_to='product_media/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Product.product')),
            ],
            options={
                'db_table': 'product_media',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Product.product')),
            ],
            options={
                'db_table': 'product_review',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecter', models.UUIDField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
            options={
                'db_table': 'collection',
                'unique_together': {('collection', 'collecter')},
            },
        ),
    ]
