name: ProductService_K3S_Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_productdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Django tests
        env:
          DATABASE_URL: postgres://postgres:testpassword@localhost:5432/test_productdb
          DJANGO_SETTINGS_MODULE: ProductService.settings
          SECRET_KEY: test-secret-key-for-github-actions
          DEBUG: False
        run: |
          python manage.py migrate
          python manage.py test
  build-and-deploy-k3s:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Save Docker Images
        run: |
          # 构建ProductService后端镜像
          docker build -t productservice-backend:${{ github.sha }} .
          docker tag productservice-backend:${{ github.sha }} productservice-backend:latest
          
          # 拉取PostgreSQL镜像
          docker pull postgres:14
          
          # 保存镜像
          docker save productservice-backend:latest | gzip > productservice-backend.tar.gz
          docker save postgres:14 | gzip > postgres-14.tar.gz

      - name: Create K3s deployment package
        run: |
          mkdir -p k3s-deploy
          cp -r k8s/* k3s-deploy/
          cp productservice-backend.tar.gz k3s-deploy/
          cp postgres-14.tar.gz k3s-deploy/
          cp docker-compose.yml k3s-deploy/
          
          # 创建部署脚本
          cat > k3s-deploy/deploy-to-k3s.sh << 'EOF'
          #!/bin/bash
          set -e
          
          echo "开始部署 ProductService 到 K3s..."
          
          # 设置kubectl别名
          alias kubectl='k3s kubectl'
          
          # 加载Docker镜像到K3s
          echo "加载Docker镜像..."
          echo "导入ProductService后端镜像..."
          k3s ctr images import productservice-backend.tar.gz
          echo "导入PostgreSQL数据库镜像..."
          k3s ctr images import postgres-14.tar.gz
          
          # 验证镜像导入
          echo "验证镜像导入..."
          k3s ctr images list | grep -E "(productservice-backend|postgres)"
          
          # 应用K8s配置
          echo "应用K8s配置..."
          k3s kubectl apply -f postgres-data-persistentvolumeclaim.yaml
          k3s kubectl apply -f db-deployment.yaml
          k3s kubectl apply -f db-service.yaml
          
          # 等待数据库启动
          echo "等待数据库启动..."
          k3s kubectl wait --for=condition=ready pod -l io.kompose.service=db --timeout=300s || {
            echo "数据库启动超时，检查日志..."
            k3s kubectl describe pod -l io.kompose.service=db
            k3s kubectl logs -l io.kompose.service=db --tail=50
            exit 1
          }
          
          # 部署后端服务
          echo "部署后端服务..."
          k3s kubectl apply -f backend-deployment.yaml
          k3s kubectl apply -f backend-service.yaml
          
          # 等待后端服务启动
          echo "等待后端服务启动..."
          k3s kubectl wait --for=condition=ready pod -l io.kompose.service=backend --timeout=300s || {
            echo "后端服务启动超时，检查日志..."
            k3s kubectl describe pod -l io.kompose.service=backend
            k3s kubectl logs -l io.kompose.service=backend --tail=50
            exit 1
          }
          
          # 检查部署状态
          echo "检查部署状态..."
          k3s kubectl get pods
          k3s kubectl get services
          
          # 获取服务端口
          NODE_PORT=$(k3s kubectl get service backend -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo "30800")
          echo "ProductService 部署完成！"
          echo "访问地址: http://localhost:$NODE_PORT"
          echo "健康检查: http://localhost:$NODE_PORT/health/"
          
          # 健康检查
          echo "执行健康检查..."
          for i in {1..10}; do
            if curl -f http://localhost:$NODE_PORT/health/ > /dev/null 2>&1; then
              echo "✅ 健康检查通过！"
              break
            elif [ $i -eq 10 ]; then
              echo "⚠️ 健康检查失败，但服务可能仍在启动中"
              echo "最近的Pod日志:"
              k3s kubectl logs -l io.kompose.service=backend --tail=20
            else
              echo "等待服务完全启动... ($i/10)"
              sleep 15
            fi
          done
          EOF
          
          chmod +x k3s-deploy/deploy-to-k3s.sh
          
          # 打包部署文件
          tar -czf ProductService.tar.gz k3s-deploy/

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to K3s Server
        run: |
          # 上传部署包到服务器
          sshpass -p "${{ secrets.ECS_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            ProductService.tar.gz \
            root@${{ secrets.ECS_IP }}:/tmp/
          
          # 在服务器上执行部署
          sshpass -p "${{ secrets.ECS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.ECS_IP }} "
            # 清理旧的部署
            rm -rf ~/ProductService
            
            # 解压新的部署包
            cd ~
            tar -xzf /tmp/ProductService.tar.gz
            mv k3s-deploy ProductService
            cd ProductService
            
            # 执行部署脚本
            ./deploy-to-k3s.sh
            
            # 清理临时文件
            rm -f /tmp/ProductService.tar.gz
            
            echo 'K3s ProductService 部署完成!'
          "
